// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClzOwy6SFfKVaA6fS1f3k6w0JuJ3Mo7NM',
    appId: '1:21627369169:web:4cdce7b78172c48ebb37f0',
    messagingSenderId: '21627369169',
    projectId: 'cmfi-daily-account',
    authDomain: 'cmfi-daily-account.firebaseapp.com',
    storageBucket: 'cmfi-daily-account.firebasestorage.app',
    measurementId: 'G-TNJN35FL53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZnG1LxQDGc6KTQhTfeZ2-2eA-lSUAQ4',
    appId: '1:21627369169:android:375872f624d0dcc5bb37f0',
    messagingSenderId: '21627369169',
    projectId: 'cmfi-daily-account',
    storageBucket: 'cmfi-daily-account.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fbIHv8uFQ7bb8NbqNRRDdZYaSjzacvw',
    appId: '1:21627369169:ios:cc875ae8cb089b11bb37f0',
    messagingSenderId: '21627369169',
    projectId: 'cmfi-daily-account',
    storageBucket: 'cmfi-daily-account.firebasestorage.app',
    androidClientId: '21627369169-796l6hf7no1g6e1q35bid71i6smqegr2.apps.googleusercontent.com',
    iosBundleId: 'com.jilengineering.dailyaccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fbIHv8uFQ7bb8NbqNRRDdZYaSjzacvw',
    appId: '1:21627369169:ios:1e2735731131927bbb37f0',
    messagingSenderId: '21627369169',
    projectId: 'cmfi-daily-account',
    storageBucket: 'cmfi-daily-account.firebasestorage.app',
    androidClientId: '21627369169-796l6hf7no1g6e1q35bid71i6smqegr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyAccount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClzOwy6SFfKVaA6fS1f3k6w0JuJ3Mo7NM',
    appId: '1:21627369169:web:e1825fb6bc1ec617bb37f0',
    messagingSenderId: '21627369169',
    projectId: 'cmfi-daily-account',
    authDomain: 'cmfi-daily-account.firebaseapp.com',
    storageBucket: 'cmfi-daily-account.firebasestorage.app',
    measurementId: 'G-V56T04MQZ3',
  );
}
